Repository halo-dev/rfcs, pull requests merged in 2022-06, with the labels that each got.

#10 feat: Add pluggable design
  plugin/assets/image-20220507180723198.png
  plugin/pluggable-design.drawio
  plugin/pluggable-design.md
Labels: approved, release-note-none, lgtm

#11 docs: fix typos and markdown-lint issues
  README.md
  identity/001-access.md
  identity/002-security.md
  identity/003-encryption.md
  plugin/pluggable-design.md
  pnpm-lock.yaml
  template.md
Labels: release-note, approved, kind/documentation, lgtm

#12 Add front-end plugin design
  plugin/pluggable-design.md
Labels: release-note, approved, lgtm

#13 Refine design of customizing API definitions in Plugin
  plugin/pluggable-design.md
Labels: approved, release-note-none, lgtm, kind/improvement
